apiVersion: v1 
kind: Pod 
metadata:
  name: nginx
spec:
  containers:
  - name: nginx
    image: nginx
  tolerations: # it will run in tainted node or normal nodes
  - key: "hardware"
    value: "gpu"
    operator: "Equal"
    effect: "NoSchedule"
