apiVersion: v1 
kind: Pod 
metadata:
  name: nginx
spec:
  containers:
  - name: nginx
    image: nginx
  tolerations:
  - key: "hardware"
    value: "gpu"
    operator: "Equal"
    effect: "NoSchedule"
  nodeSelector: # label node. it will select tainted node and pod run in that node because using tolerations
    hardware: gpu