apiVersion: v1 
kind: Pod
metadata: 
  name: nginx
spec:
  affinity: 
    nodeAffinity:
    # preferredscheduling means soft rule
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference:
          matchExpressions:
          - key: another-node-label-key
            operator: In
            values:
            - another-node-label-value
  containers:
  - name: nginx
    image: nginx
  tolerations:
  - key: "hardware"
    operator: "Equal"
    value: "gpu"
    effect: "NoSchedule"