# pod affinity both pod-1 and pod-2 runs on same node
apiVersion: v1 
kind: Pod
metadata:
  name: pod-1
  labels:
    purpose: affinity
spec:
  containers:
  - name: nginx
    image: nginx

---
# this pod-2 will be run on only pod-1 node 
apiVersion: v1 
kind: Pod
metadata:
  name: pod-2
spec:
  affinity: 
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: purpose
            operator: In 
            values: 
            - affinity
        topologyKey: topology.kubernetes.io/zone
  containers:
  - name: nginx
    image: nginx

---
# podAntiAffinty means the pod will not create on match Expressions
apiVersion: v1 
kind: Pod
metadata:
  name: pod-3
spec:
  affinity: 
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: purpose
              operator: In 
              values:
              - affinity
          topologyKey: topology.kubernetes.io/zone
  containers:
  - name: nginx
    image: nginx
    
