apiVersion: apps/v1
kind: Deployment 
metadata:
  name: redis-cache
spec:
  replicas: 3
  selector: 
    matchLabels:
      app: store
  template:
    metadata:
      labels:
        app: store
    spec: 
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In 
                values:
                - store
            topologyKey: kubernetes.io/hostname
      containers:
      - name: redis-server
        image: redis:3.2-alpine

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web-server
  template:
    metadata:
      labels:
        app: web-server
    spec:
      affinity: 
        # unlike the web-server labels and place each pod in diff nodes
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  app: web-server
              topologyKey: kubernetes.io/hostname
        # like the redis labels and place each web-server pods in each redis-server pods
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key:  app
                operator: In 
                values:
                - store
            topologyKey: kubernetes.io/hostname
      containers:
      - name: web-app
        image: nginx:1.16-alpine

