apiVersion: apps/v1
kind: Deployment 
metadata:
  name: redis-cache
spec:
  replicas: 3
  selector: 
    matchLabels:
      app: store
  template:
    metadata:
      labels:
        app: store
    spec: 
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In 
                values:
                - store
            topologyKey: kubernetes.io/hostname
      containers:
      - name: redis-server
        image: redis:3.2-alpine

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-server
spec:
  replicas: 3
  matchLabels:
    app: web-server
  template:
    metadata:
      labels:
        app: web-server
    spec:
      affinity: 
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In 
                values:
                - web-server
            topologyKey: kubernetes.io/hostname
      containers:
      - name: web-app
        image: nginx:1.16-alpine

